Description: >

  This template deploys a deploys a highly available ECS cluster using an AutoScaling Group, with 
  ECS hosts distributed across multiple Availability Zones. Then, it deploys the Clara Train SDK 
  as an ECS services from containers published in the NVIDIA repository or Amazon EC2 Container 
  Registry (Amazon ECR). (qs-1ql5cpbht)

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
        - VPC
        - VPCCIDR
        - PrivateSubnet1AID
        - PrivateSubnet2AID
        - PublicSubnet1ID
        - PublicSubnet2ID
      - Label:
          default: EFS configuration
        Parameters:
        - EFSDeletionPolicy
        - PerformanceMode
      - Label:
          default: ECS EC2 instance configuration
        Parameters:
        - KeyName
        - ECSHostInstanceType
      - Label:
          default: ECS cluster configuration
        Parameters:
        - SourceCidrIP
        - UseHTTPS
        - CertificateID
        - ClusterSize
        - DesiredServiceCount
        - BastionSecurityGroupID
      - Label:
          default: AWS Quick Start configuration
        Parameters:      
        - QSS3BucketName
        - QSS3BucketRegion
        - QSS3KeyPrefix
    ParameterLabels:
      VPC:
        default: VPC ID
      VPCCIDR:
        default: VPC CIDR
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PrivateSubnet1AID:
        default: Private subnet 1 ID
      PrivateSubnet2AID:
        default: Private subnet 2 ID
      EFSDeletionPolicy:
        default: EFS deletion policy
      PerformanceMode:
        default: EFS performance mode
      KeyName:
        default: Key pair name
      ECSHostInstanceType:
        default: ECS EC2 instance type
      SourceCidrIP: 
        default: Allowed load balancer external access CIDR 
      UseHTTPS:
        default: Enable end-to-end encryption of connections to the AI-Assisted Annotation service
      CertificateID:
        default: ARN for the Certificate to use for TLS. Otherwise leave blank for HTTP
      ClusterSize:
        default: Number of ECS hosts
      DesiredServiceCount:
        default: Number of instances of this Clara Train task    
      BastionSecurityGroupID:
        default: Linux bastion security group
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  VPC:
    Description: ID of the VPC this ECS cluster should be deployed to
    Type: AWS::EC2::VPC::Id
  VPCCIDR:
    Description: The CIDR block of the VPC this ECS cluster should be deployed to
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Type: String
  PublicSubnet1ID:
    Description: ID of the public subnet 1
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2ID:
    Description: ID of the public subnet 2
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet1AID:
    Description: ID of the private subnet 1
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2AID:
    Description: ID of the private subnet 2
    Type: AWS::EC2::Subnet::Id
  EFSDeletionPolicy:
    AllowedValues:
      - Delete
      - Retain
    Default: Delete
    Description: Retain or delete the Amazon EFS resources after CloudFormation stack deletion.
    Type: String
  PerformanceMode:
    AllowedValues:
      - generalPurpose
      - maxIO
    Default: generalPurpose
    Description: The performance mode of the EFS file system.
    Type: String
  ECSHostInstanceType:
    Description: Instance type for ECS hosts
    Type: String
    Default: p3.2xlarge
  ClusterSize:
    Description: Number of ECS hosts
    Type: Number
    Default: 1
  DesiredServiceCount:
    Description: Number of Clara service instances
    Type: Number
    Default: 1
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), dots (.) and forward slash (/). The prefix should end with a forward slash (/).
    Default: 'quickstart-nvidia-imaging-clara-train/'
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), dots
      (.) and forward slash (/) and it should end with a forward slash (/).
    Type: String
  SourceCidrIP:
    Description: CIDR block from which connections to the load balancer will be accepted
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/0-32
    Type: String
  BastionSecurityGroupID: 
    Description: The Security Group of the bastion host, allowed to connect to private IPs of ECS hosts
    Type: AWS::EC2::SecurityGroup::Id
  UseHTTPS:
    Description: The default value 'HTTPS' enables end-to-end encryption of connections to annotation server. Choose HTTP to enable unencrypted connections (not recommended for production use).
    AllowedValues:
     - HTTPS
     - HTTP
    Default: HTTPS
    Type: String
  CertificateID:
    Description: The ARN of the Certificate to use for TLS. You must specify this value if UseHTTPS is set to HTTPS.
    Default: ''
    Type: String  
  

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Mappings:
  Defaults:
    Clara:
      Uri: nvcr.io/nvidia/clara-train-sdk:v4.1

Resources:

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/efs.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !Ref VPC
        VPCCIDR: !Ref VPCCIDR
        Subnets: !Join [",", [!Ref PrivateSubnet1AID, !Ref PrivateSubnet2AID]]
        DeletionPolicy: !Ref EFSDeletionPolicy
        PerformanceMode: !Ref PerformanceMode

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/load-balancer.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !Ref VPC
        Subnets: !Join [",", [!Ref PublicSubnet1ID, !Ref PublicSubnet2ID]]
        SourceCidrIP: !Ref SourceCidrIP
        UseHTTPS: !Ref UseHTTPS
        CertificateID: !Ref CertificateID

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/ecs-cluster.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: !Ref ECSHostInstanceType
        ClusterSize: !Ref ClusterSize
        VPC: !Ref VPC
        Subnets: !Join [",", [!Ref PrivateSubnet1AID, !Ref PrivateSubnet2AID]]
        LoadBalancerSecurityGroup: !GetAtt ALB.Outputs.LoadBalancerSecurityGroup
        EFSSecurityGroup: !GetAtt EFS.Outputs.EFSSecurityGroup
        KeyName: !Ref KeyName
        BastionSecurityGroupID: !Ref BastionSecurityGroupID
        ElasticFileSystemDnsName: !GetAtt EFS.Outputs.ElasticFileSystemDnsName

  ClaraService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/service.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPC: !Ref VPC
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: !Ref DesiredServiceCount
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /
        ECSServiceAutoScalingRoleARN: !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        ElasticFileSystemDnsName: !GetAtt EFS.Outputs.ElasticFileSystemDnsName
        ContainerImageRegistry: !FindInMap [ Defaults, Clara, Uri ]
        UseHTTPS: !Ref UseHTTPS

Outputs:

  ElasticFileSystemDnsName:
    Description: DNS name for the Amazon EFS file system.
    Value: !GetAtt EFS.Outputs.ElasticFileSystemDnsName

  ClaraServiceUrl:
    Description: The URL endpoint for the Clara Train service
    Value: !GetAtt ALB.Outputs.LoadBalancerUrl